// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using Models;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace EContext.Models;

public partial class Account:BaseEntity<int>
{


   
    [StringLength(50)]
    public string? AccountNumber { get; set; }

  
    [StringLength(100)]
    public string? AccountNameAr { get; set; }

    [StringLength(100)]
    public string? AccountNameEn { get; set; }

    [Column("BranchID")]
    public int? BranchId { get; set; }

    [ForeignKey("BranchId")]
    [InverseProperty("Accounts")]
    public virtual Branch Branch { get; set; }

    [InverseProperty("Account")]
    public virtual ICollection<Jvdetail> Jvdetails { get; set; } = new List<Jvdetail>();
}