// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using Models;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace EContext.Models;

public partial class Branch:BaseEntity<int>
{
  

  
    [StringLength(50)]
    public string? BranchCode { get; set; }

    
    [StringLength(50)]
    public string? BranchNameAr { get; set; }

    [StringLength(50)]
    public string? BranchNameEn { get; set; }

    [InverseProperty("Branch")]
    public virtual ICollection<Account> Accounts { get; set; } = new List<Account>();

    [InverseProperty("Branch")]
    public virtual ICollection<City> Cities { get; set; } = new List<City>();

    [InverseProperty("Branch")]
    public virtual ICollection<Jvdetail> Jvdetails { get; set; } = new List<Jvdetail>();

    [InverseProperty("Branch")]
    public virtual ICollection<Jv> Jvs { get; set; } = new List<Jv>();

    [InverseProperty("Branch")]
    public virtual ICollection<Jvtype> Jvtypes { get; set; } = new List<Jvtype>();

    [InverseProperty("Branch")]
    public virtual ICollection<SubAccount> SubAccounts { get; set; } = new List<SubAccount>();

    [InverseProperty("Branch")]
    public virtual ICollection<SubAccountsClient> SubAccountsClients { get; set; } = new List<SubAccountsClient>();

    [InverseProperty("Branch")]
    public virtual ICollection<SubAccountsLevel> SubAccountsLevels { get; set; } = new List<SubAccountsLevel>();
}