// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using Models;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace EContext.Models;

public partial class City:BaseEntity<int>
{


    [StringLength(50)]
    public string CityCode { get; set; }

    [StringLength(100)]
    public string CityNameAr { get; set; }

    [StringLength(100)]
    public string CityNameEn { get; set; }

    [Column("BranchID")]
    public int? BranchId { get; set; }

    [ForeignKey("BranchId")]
    [InverseProperty("Cities")]
    public virtual Branch Branch { get; set; }

    [InverseProperty("City")]
    public virtual ICollection<SubAccountsClient> SubAccountsClients { get; set; } = new List<SubAccountsClient>();
}