// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using Models;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace EContext.Models;

[Table("JV")]
public partial class Jv:BaseEntity<int>
{
  

  
    [Column("JVNo")]
    [StringLength(50)]
    public int ?Jvno { get; set; } 

    [Column("JVDate", TypeName = "datetime")]
    public DateTime? Jvdate { get; set; }

    [Column("JVTypeID")]
    public int? JvtypeId { get; set; }

    [Column(TypeName = "numeric(22, 8)")]
    public decimal? TotalDebit { get; set; }

    [Column(TypeName = "numeric(22, 8)")]
    public decimal? TotalCredit { get; set; }

    [StringLength(50)]
    public string? ReceiptNo { get; set; } = "JV-";

    [StringLength(1000)]
    public string? Notes { get; set; }

    [Column("BranchID")]
    public int? BranchId { get; set; }

    [ForeignKey("BranchId")]
    [InverseProperty("Jvs")]
    public virtual Branch Branch { get; set; }

    [InverseProperty("Jv")]
    public virtual ICollection<Jvdetail> Jvdetails { get; set; } = new List<Jvdetail>();

    [ForeignKey("JvtypeId")]
    [InverseProperty("Jvs")]
    public virtual Jvtype Jvtype { get; set; }
}