// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using Models;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace EContext.Models;

[Table("JVDetails")]
public partial class Jvdetail:BaseEntity<int>
{
  

    [Column("JVID")]
    public int Jvid { get; set; }

    [Column("AccountID")]
    public int AccountId { get; set; }

    [Column("SubAccountID")]
    public int? SubAccountId { get; set; }

    [Column(TypeName = "numeric(22, 8)")]
    public decimal? Debit { get; set; }

    [Column(TypeName = "numeric(22, 8)")]
    public decimal? Credit { get; set; }

    [Column(TypeName = "numeric(22, 8)")]
    public decimal LocalDebit { get; set; }

    [Column(TypeName = "numeric(22, 8)")]
    public decimal LocalCredit { get; set; }

    public bool IsDocumented { get; set; }

    [StringLength(1000)]
    public string Notes { get; set; }

    [Column("BranchID")]
    public int? BranchId { get; set; }

    [ForeignKey("AccountId")]
    [InverseProperty("Jvdetails")]
    public virtual Account Account { get; set; }

    [ForeignKey("BranchId")]
    [InverseProperty("Jvdetails")]
    public virtual Branch Branch { get; set; }

    [ForeignKey("Jvid")]
    [InverseProperty("Jvdetails")]
    public virtual Jv Jv { get; set; }

    [ForeignKey("SubAccountId")]
    [InverseProperty("Jvdetails")]
    public virtual SubAccount SubAccount { get; set; }
}