// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using Models;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace EContext.Models;

[Table("JVTypes")]
public partial class Jvtype:BaseEntity<int>
{
 

    [Column("JVTypeNameAr")]
    [StringLength(100)]
    public string? JvtypeNameAr { get; set; }

    [Column("JVTypeNameEn")]
    [StringLength(100)]
    public string JvtypeNameEn { get; set; }

    [Column("BranchID")]
    public int? BranchId { get; set; }

    [ForeignKey("BranchId")]
    [InverseProperty("Jvtypes")]
    public virtual Branch Branch { get; set; }

    [InverseProperty("Jvtype")]
    public virtual ICollection<Jv> Jvs { get; set; } = new List<Jv>();
}