// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using Models;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace EContext.Models;

[Table("SubAccountsClient")]
public partial class SubAccountsClient:BaseEntity<int>
{
 

   
    [StringLength(50)]
    public string? ClientNo { get; set; }

    [Column("SubAccountID")]
    public int? SubAccountId { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? BirthDate { get; set; }

    [Column("CityID")]
    public int? CityId { get; set; }

    [Column(TypeName = "numeric(18, 8)")]
    public decimal? CreditLimit { get; set; }

    public bool? IsDiscountTax { get; set; }

    public bool? IsActive { get; set; }

    [StringLength(500)]
    public string? Notes { get; set; }

    [Column("BranchID")]
    public int? BranchId { get; set; }

    [ForeignKey("BranchId")]
    [InverseProperty("SubAccountsClients")]
    public virtual Branch Branch { get; set; }

    [ForeignKey("CityId")]
    [InverseProperty("SubAccountsClients")]
    public virtual City City { get; set; }

    [ForeignKey("SubAccountId")]
    [InverseProperty("SubAccountsClients")]
    public virtual SubAccount SubAccount { get; set; }
}