// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using Models;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace EContext.Models;

public partial class SubAccount:BaseEntity<int>
{
  

   
    [StringLength(50)]
    public string SubAccountNumber { get; set; }

 
    [StringLength(100)]
    public string? SubAccountNameAr { get; set; }

    [StringLength(100)]
    public string SubAccountNameEn { get; set; }

    [Column("ParentID")]
    public int? ParentId { get; set; }

    public bool? IsMain { get; set; }

    [Column("LevelID")]
    public int? LevelId { get; set; }

    [Column("SubAccountTypeID")]
    public int? SubAccountTypeId { get; set; }

    [Column("BranchID")]
    public int? BranchId { get; set; }

    [ForeignKey("BranchId")]
    [InverseProperty("SubAccounts")]
    public virtual Branch Branch { get; set; }

    [InverseProperty("Parent")]
    public virtual ICollection<SubAccount> InverseParent { get; set; } = new List<SubAccount>();

    [InverseProperty("SubAccount")]
    public virtual ICollection<Jvdetail> Jvdetails { get; set; } = new List<Jvdetail>();

    [ForeignKey("LevelId")]
    [InverseProperty("SubAccounts")]
    public virtual SubAccountsLevel Level { get; set; }

    [ForeignKey("ParentId")]
    [InverseProperty("InverseParent")]
    public virtual SubAccount Parent { get; set; }

    [ForeignKey("SubAccountTypeId")]
    [InverseProperty("SubAccounts")]
    public virtual SubAccountsType SubAccountType { get; set; }

    [InverseProperty("SubAccount")]
    public virtual ICollection<SubAccountsClient>? SubAccountsClients { get; set; } = new List<SubAccountsClient>();
}