// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using Models;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace EContext.Models;

public partial class SubAccountsType:BaseEntity<int>
{
  

   
    [StringLength(100)]
    public string? SubAccountTypeNameAr { get; set; }

    [StringLength(100)]
    public string? SubAccountTypeNameEn { get; set; }

    [Column("BranchID")]
    public int? BranchId { get; set; } = 1;

    [InverseProperty("SubAccountType")]
    public virtual ICollection<SubAccount>? SubAccounts { get; set; } = new List<SubAccount>();
}