// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using Models;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace EContext.Models;

[Table("SubAccounts_Levels")]
public partial class SubAccountsLevel:BaseEntity<int>
{
 

    public int? Width { get; set; }

    [Column("BranchID")]
    public int? BranchId { get; set; }

    [ForeignKey("BranchId")]
    [InverseProperty("SubAccountsLevels")]
    public virtual Branch Branch { get; set; }

    [InverseProperty("Level")]
    public virtual ICollection<SubAccount> SubAccounts { get; set; } = new List<SubAccount>();
}